#include "extended_mumford_projective.hpp"

ExtendedProjectiveMumford::ExtendedProjectiveMumford(){
    this->f = ExtendedPolynomial();
    this->h = ExtendedPolynomial();
    this->U1 = ExtendedNumber::ZERO();
    this->U0 = ExtendedNumber::ONE();
    this->V1 = ExtendedNumber::ZERO();
    this->V0 = ExtendedNumber::ZERO();
    this->Z = ExtendedNumber::ONE();
}

ExtendedProjectiveMumford::ExtendedProjectiveMumford(ExtendedPolynomial f, ExtendedPolynomial h){
    this->f = f;
    this->h = h;
    this->U1 = ExtendedNumber::ZERO();
    this->U0 = ExtendedNumber::ONE();
    this->V1 = ExtendedNumber::ZERO();
    this->V0 = ExtendedNumber::ZERO();
    this->Z = ExtendedNumber::ONE();
}

ExtendedProjectiveMumford::ExtendedProjectiveMumford(ExtendedPolynomial f, ExtendedPolynomial h, ExtendedNumber U1, ExtendedNumber U0, ExtendedNumber V1, ExtendedNumber V0, ExtendedNumber Z, ExtendedNumber W1, ExtendedNumber W0){
    this->f = f;
    this->h = h;
    this->U1 = U1;
    this->U0 = U0;
    this->V1 = V1;
    this->V0 = V0;
    this->Z = Z;
    this->W1 = W1;
    this->W0 = W0;
}

ExtendedProjectiveMumford::ExtendedProjectiveMumford(ExtendedPolynomial f, ExtendedPolynomial h, ExtendedNumber U1, ExtendedNumber U0, ExtendedNumber V1, ExtendedNumber V0, ExtendedNumber Z){
    this->f = f;
    this->h = h;
    this->U1 = U1;
    this->U0 = U0;
    this->V1 = V1;
    this->V0 = V0;
    this->Z = Z;
    this->W1 = U1 * U1;
    this->W0 = U1 * U0;
}

ExtendedProjectiveMumford::ExtendedProjectiveMumford(ExtendedPolynomial f, ExtendedPolynomial h, ExtendedNumber U1, ExtendedNumber U0, ExtendedNumber V1, ExtendedNumber V0){
    this->f = f;
    this->h = h;
    this->U1 = U1;
    this->U0 = U0;
    this->V1 = V1;
    this->V0 = V0;
    this->Z = ExtendedNumber::ONE();
    this->W1 = U1 * U1;
    this->W0 = U1 * U0;
}

ExtendedProjectiveMumford ExtendedProjectiveMumford::operator * (const mpz_class& k_) const{
    ExtendedPolynomial f = this->f;
    ExtendedPolynomial h = this->h;
    mpz_class k = k_;

    // double-and-add method によりスカラー倍を計算する．

    // 連除法で 2 進数に変換．
    mpz_class two = 2;
    int count = 0;
    std::vector<int> bits;
    while(true){
        mpz_class rem = k % 2;
        bits.push_back((int) rem.get_si());

        k = k / 2;
        ++count;

        if(k < 1){
            break;
        }
    }

    ExtendedProjectiveMumford D = ExtendedProjectiveMumford::zero(f, h);
    ExtendedProjectiveMumford now = *this;
    for(int i = 0; i < count; ++i){
        if(bits[i] == 1){
            if(D.isZero()){
                D = now;
            }else if(now.isZero()){
                // D = D;
            }else{
                D = D.LangeAdd(now);
            }
            //D.print();
        }
        now = now.LangeDoubling();
    }
    return D;
}



ExtendedProjectiveMumford ExtendedProjectiveMumford::LangeAdd(const ExtendedProjectiveMumford& m) const{
    //std::cout << "Projective Lange Addition." << std::endl;
    // 64M, 6S
    mpz_t temp;
    mpz_init(temp);
    ExtendedNumber tempd;
    mpz_t tempd1, tempd2, tempd3, tempd4;
    mpz_init(tempd1);
    mpz_init(tempd2);
    mpz_init(tempd3);
    mpz_init(tempd4);
    ExtendedNumber temp1, temp2;
    // 1. 終結式を計算．
    // 8M, 2S
    ExtendedNumber z1, z2, z3, r, rs;
    mpz_mul(tempd1, this->U1.re, m.Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, this->U1.im, m.Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, this->U1.re, this->U1.im);
    mpz_add(tempd4, m.Z.re, m.Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(z1.re, tempd.re);
    mpz_set(z1.im, tempd.im);
    mpz_mul(tempd1, m.U1.re, this->Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, m.U1.im, this->Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, m.U1.re, m.U1.im);
    mpz_add(tempd4, this->Z.re, this->Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_sub(z1.re, z1.re, temp1.re);
    mpz_sub(z1.im, z1.im, temp1.im);
    mpz_mul(tempd1, m.U0.re, this->Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, m.U0.im, this->Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, m.U0.re, m.U0.im);
    mpz_add(tempd4, this->Z.re, this->Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(z2.re, tempd.re);
    mpz_set(z2.im, tempd.im);
    mpz_mul(tempd1, this->U0.re, m.Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, this->U0.im, m.Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, this->U0.re, this->U0.im);
    mpz_add(tempd4, m.Z.re, m.Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_sub(z2.re, z2.re, temp1.re);
    mpz_sub(z2.im, z2.im, temp1.im);
    mpz_mul(tempd1, this->U1.re, z1.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, this->U1.im, z1.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, this->U1.re, this->U1.im);
    mpz_add(tempd4, z1.re, z1.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(z3.re, tempd.re);
    mpz_set(z3.im, tempd.im);
    mpz_mul(tempd1, z2.re, this->Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, z2.im, this->Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, z2.re, z2.im);
    mpz_add(tempd4, this->Z.re, this->Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_add(z3.re, z3.re, temp1.re);
    mpz_add(z3.im, z3.im, temp1.im);
    mpz_mul(tempd1, z1.re, z1.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, z1.im, z1.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, z1.re, z1.im);
    mpz_add(tempd4, z1.re, z1.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(r.re, tempd.re);
    mpz_set(r.im, tempd.im);
    mpz_mul(tempd1, r.re, this->U0.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, r.im, this->U0.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, r.re, r.im);
    mpz_add(tempd4, this->U0.re, this->U0.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(r.re, tempd.re);
    mpz_set(r.im, tempd.im);
    mpz_mul(tempd1, z2.re, z3.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, z2.im, z3.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, z2.re, z2.im);
    mpz_add(tempd4, z3.re, z3.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_add(r.re, temp1.re, r.re);
    mpz_add(r.im, temp1.im, r.im);
    mpz_mul(tempd1, r.re, r.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, r.im, r.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, r.re, r.im);
    mpz_add(tempd4, r.re, r.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(rs.re, tempd.re);
    mpz_set(rs.im, tempd.im);

    // 2. almost inverse を計算．
    // 6M
    //ExtendedNumber inv1 = z1;
    //ExtendedNumber inv0 = z3;
    ExtendedNumber w0, w1, w2, w3;
    mpz_mul(tempd1, this->V0.re, m.Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, this->V0.im, m.Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, this->V0.re, this->V0.im);
    mpz_add(tempd4, m.Z.re, m.Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(w0.re, tempd.re);
    mpz_set(w0.im, tempd.im);
    mpz_mul(tempd1, m.V0.re, this->Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, m.V0.im, this->Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, m.V0.re, m.V0.im);
    mpz_add(tempd4, this->Z.re, this->Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_sub(w0.re, w0.re, temp1.re);
    mpz_sub(w0.im, w0.im, temp1.im);
    mpz_mul(tempd1, this->V1.re, m.Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, this->V1.im, m.Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, this->V1.re, this->V1.im);
    mpz_add(tempd4, m.Z.re, m.Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(w1.re, tempd.re);
    mpz_set(w1.im, tempd.im);
    mpz_mul(tempd1, m.V1.re, this->Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, m.V1.im, this->Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, m.V1.re, m.V1.im);
    mpz_add(tempd4, this->Z.re, this->Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_sub(w1.re, w1.re, temp1.re);
    mpz_sub(w1.im, w1.im, temp1.im);
    mpz_mul(tempd1, z3.re, w0.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, z3.im, w0.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, z3.re, z3.im);
    mpz_add(tempd4, w0.re, w0.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(w2.re, tempd.re);
    mpz_set(w2.im, tempd.im);
    mpz_mul(tempd1, z1.re, w1.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, z1.im, w1.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, z1.re, z1.im);
    mpz_add(tempd4, w1.re, w1.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(w3.re, tempd.re);
    mpz_set(w3.im, tempd.im);

    // 3. s を計算．
    // 4M
    ExtendedNumber s1, s0;
    mpz_add(s1.re, w0.re, w1.re);
    mpz_add(s1.im, w0.im, w1.im);
    mpz_mul(tempd1, this->Z.re, z1.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, this->Z.im, z1.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, this->Z.re, this->Z.im);
    mpz_add(tempd4, z1.re, z1.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_add(temp1.re, temp1.re, z3.re);
    mpz_add(temp1.im, temp1.im, z3.im);
    mpz_mul(tempd1, s1.re, temp1.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, s1.im, temp1.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, s1.re, s1.im);
    mpz_add(tempd4, temp1.re, temp1.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(s1.re, tempd.re);
    mpz_set(s1.im, tempd.im);
    mpz_sub(s1.re, s1.re, w2.re);
    mpz_sub(s1.im, s1.im, w2.im);
    mpz_add(temp1.re, this->Z.re, this->U1.re);
    mpz_add(temp1.im, this->Z.im, this->U1.im);
    mpz_mul(tempd1, w3.re, temp1.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, w3.im, temp1.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, w3.re, w3.im);
    mpz_add(tempd4, temp1.re, temp1.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_sub(s1.re, s1.re, temp1.re);
    mpz_sub(s1.im, s1.im, temp1.im);
    mpz_mul(tempd1, this->U0.re, w3.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, this->U0.im, w3.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, this->U0.re, this->U0.im);
    mpz_add(tempd4, w3.re, w3.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(s0.re, tempd.re);
    mpz_set(s0.im, tempd.im);
    mpz_sub(s0.re, w2.re, s0.re);
    mpz_sub(s0.im, w2.im, s0.im);

    // 4. l を計算．全体に (Z1 Z2)^3 がかかっている．
    // 5M
    ExtendedNumber l3, l2, l1, l0;
    mpz_mul(tempd1, s1.re, m.Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, s1.im, m.Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, s1.re, s1.im);
    mpz_add(tempd4, m.Z.re, m.Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(l3.re, tempd.re);
    mpz_set(l3.im, tempd.im);
    mpz_mul(tempd1, s1.re, m.U1.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, s1.im, m.U1.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, s1.re, s1.im);
    mpz_add(tempd4, m.U1.re, m.U1.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(l2.re, tempd.re);
    mpz_set(l2.im, tempd.im);
    mpz_mul(tempd1, s0.re, m.U0.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, s0.im, m.U0.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, s0.re, s0.im);
    mpz_add(tempd4, m.U0.re, m.U0.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(l0.re, tempd.re);
    mpz_set(l0.im, tempd.im);
    mpz_add(l1.re, s1.re, s0.re);
    mpz_add(l1.im, s1.im, s0.im);
    mpz_add(temp1.re, m.U1.re, m.U0.re);
    mpz_add(temp1.im, m.U1.im, m.U0.im);
    mpz_mul(tempd1, l1.re, temp1.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, l1.im, temp1.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, l1.re, l1.im);
    mpz_add(tempd4, temp1.re, temp1.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(l1.re, tempd.re);
    mpz_set(l1.im, tempd.im);
    mpz_sub(l1.re, l1.re, l2.re);
    mpz_sub(l1.im, l1.im, l2.im);
    mpz_sub(l1.re, l1.re, l0.re);
    mpz_sub(l1.im, l1.im, l0.im);
    mpz_mul(tempd1, s0.re, m.Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, s0.im, m.Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, s0.re, s0.im);
    mpz_add(tempd4, m.Z.re, m.Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_add(l2.re, temp1.re, l2.re);
    mpz_add(l2.im, temp1.im, l2.im);

    // 5. U' を計算．全体に (Z1 Z2)^6 がかかっている．
    // 18M, 1S
    ExtendedNumber f5Z2, f6U21, rV21;
    mpz_mul(tempd1, this->f.coeff[5].re, m.Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, this->f.coeff[5].im, m.Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, this->f.coeff[5].re, this->f.coeff[5].im);
    mpz_add(tempd4, m.Z.re, m.Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(f5Z2.re, tempd.re);
    mpz_set(f5Z2.im, tempd.im);
    mpz_mul(tempd1, this->f.coeff[6].re, m.U1.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, this->f.coeff[6].im, m.U1.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, this->f.coeff[6].re, this->f.coeff[6].im);
    mpz_add(tempd4, m.U1.re, m.U1.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(f6U21.re, tempd.re);
    mpz_set(f6U21.im, tempd.im);
    mpz_mul(tempd1, r.re, m.V1.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, r.im, m.V1.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, r.re, r.im);
    mpz_add(tempd4, m.V1.re, m.V1.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(rV21.re, tempd.re);
    mpz_set(rV21.im, tempd.im);

    ExtendedNumber t4, t3, t2;
    mpz_mul(tempd1, rs.re, m.Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, rs.im, m.Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, rs.re, rs.im);
    mpz_add(tempd4, m.Z.re, m.Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(t4.re, tempd.re);
    mpz_set(t4.im, tempd.im);
    mpz_mul(tempd1, t4.re, this->f.coeff[6].re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, t4.im, this->f.coeff[6].im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, t4.re, t4.im);
    mpz_add(tempd4, this->f.coeff[6].re, this->f.coeff[6].im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(t4.re, tempd.re);
    mpz_set(t4.im, tempd.im);
    mpz_mul(tempd1, s1.re, l3.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, s1.im, l3.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, s1.re, s1.im);
    mpz_add(tempd4, l3.re, l3.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_sub(t4.re, temp1.re, t4.re);
    mpz_sub(t4.im, temp1.im, t4.im);
    mpz_mul(tempd1, t4.re, m.Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, t4.im, m.Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, t4.re, t4.im);
    mpz_add(tempd4, m.Z.re, m.Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(t4.re, tempd.re);
    mpz_set(t4.im, tempd.im);

    mpz_mul(tempd1, l2.re, s1.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, l2.im, s1.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, l2.re, l2.im);
    mpz_add(tempd4, s1.re, s1.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(t3.re, tempd.re);
    mpz_set(t3.im, tempd.im);
    mpz_mul(tempd1, l3.re, s0.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, l3.im, s0.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, l3.re, l3.im);
    mpz_add(tempd4, s0.re, s0.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_add(t3.re, t3.re, temp1.re);
    mpz_add(t3.im, t3.im, temp1.im);
    mpz_sub(temp1.re, f5Z2.re, f6U21.re);
    mpz_sub(temp1.im, f5Z2.im, f6U21.im);
    mpz_mul(tempd1, temp1.re, rs.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, temp1.im, rs.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, temp1.re, temp1.im);
    mpz_add(tempd4, rs.re, rs.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_sub(t3.re, t3.re, temp1.re);
    mpz_sub(t3.im, t3.im, temp1.im);
    mpz_mul(tempd1, t3.re, m.Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, t3.im, m.Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, t3.re, t3.im);
    mpz_add(tempd4, m.Z.re, m.Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(t3.re, tempd.re);
    mpz_set(t3.im, tempd.im);

    mpz_add(t2.re, l1.re, rV21.re);
    mpz_add(t2.im, l1.im, rV21.im);
    mpz_add(t2.re, t2.re, rV21.re);
    mpz_add(t2.im, t2.im, rV21.im);
    mpz_mul(tempd1, t2.re, s1.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, t2.im, s1.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, t2.re, t2.im);
    mpz_add(tempd4, s1.re, s1.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(t2.re, tempd.re);
    mpz_set(t2.im, tempd.im);
    mpz_mul(tempd1, s0.re, l2.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, s0.im, l2.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, s0.re, s0.im);
    mpz_add(tempd4, l2.re, l2.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_add(t2.re, t2.re, temp1.re);
    mpz_add(t2.im, t2.im, temp1.im);
    mpz_mul(tempd1, t2.re, m.Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, t2.im, m.Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, t2.re, t2.im);
    mpz_add(tempd4, m.Z.re, m.Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(t2.re, tempd.re);
    mpz_set(t2.im, tempd.im);
    mpz_mul(tempd1, this->f.coeff[4].re, m.Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, this->f.coeff[4].im, m.Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, this->f.coeff[4].re, this->f.coeff[4].im);
    mpz_add(tempd4, m.Z.re, m.Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_mul(tempd1, this->f.coeff[6].re, m.U0.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, this->f.coeff[6].im, m.U0.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, this->f.coeff[6].re, this->f.coeff[6].im);
    mpz_add(tempd4, m.U0.re, m.U0.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp2.re, tempd.re);
    mpz_set(temp2.im, tempd.im);
    mpz_sub(temp1.re, temp1.re, temp2.re);
    mpz_sub(temp1.im, temp1.im, temp2.im);
    mpz_mul(tempd1, temp1.re, m.Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, temp1.im, m.Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, temp1.re, temp1.im);
    mpz_add(tempd4, m.Z.re, m.Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_sub(temp2.re, f5Z2.re, f6U21.re);
    mpz_sub(temp2.im, f5Z2.im, f6U21.im);
    mpz_mul(tempd1, m.U1.re, temp2.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, m.U1.im, temp2.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, m.U1.re, m.U1.im);
    mpz_add(tempd4, temp2.re, temp2.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp2.re, tempd.re);
    mpz_set(temp2.im, tempd.im);
    mpz_sub(temp1.re, temp1.re, temp2.re);
    mpz_sub(temp1.im, temp1.im, temp2.im);
    mpz_mul(tempd1, temp1.re, rs.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, temp1.im, rs.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, temp1.re, temp1.im);
    mpz_add(tempd4, rs.re, rs.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_sub(t2.re, t2.re, temp1.re);
    mpz_sub(t2.im, t2.im, temp1.im);
    
    // 8M, 2S
    ExtendedNumber t4U11, t3Z1, Ud2, Ud1, Ud0, ZdS;
    mpz_mul(tempd1, t4.re, this->U1.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, t4.im, this->U1.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, t4.re, t4.im);
    mpz_add(tempd4, this->U1.re, this->U1.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(t4U11.re, tempd.re);
    mpz_set(t4U11.im, tempd.im);
    mpz_mul(tempd1, t3.re, this->Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, t3.im, this->Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, t3.re, t3.im);
    mpz_add(tempd4, this->Z.re, this->Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(t3Z1.re, tempd.re);
    mpz_set(t3Z1.im, tempd.im);
    mpz_mul(tempd1, t4.re, this->Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, t4.im, this->Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, t4.re, t4.im);
    mpz_add(tempd4, this->Z.re, this->Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(Ud2.re, tempd.re);
    mpz_set(Ud2.im, tempd.im);
    mpz_mul(tempd1, Ud2.re, this->Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, Ud2.im, this->Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, Ud2.re, Ud2.im);
    mpz_add(tempd4, this->Z.re, this->Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(Ud2.re, tempd.re);
    mpz_set(Ud2.im, tempd.im);
    mpz_sub(Ud1.re, t3Z1.re, t4U11.re);
    mpz_sub(Ud1.im, t3Z1.im, t4U11.im);
    mpz_mul(tempd1, Ud1.re, this->Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, Ud1.im, this->Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, Ud1.re, Ud1.im);
    mpz_add(tempd4, this->Z.re, this->Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(Ud1.re, tempd.re);
    mpz_set(Ud1.im, tempd.im);
    mpz_mul(tempd1, t2.re, this->Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, t2.im, this->Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, t2.re, t2.im);
    mpz_add(tempd4, this->Z.re, this->Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(Ud0.re, tempd.re);
    mpz_set(Ud0.im, tempd.im);
    mpz_mul(tempd1, t4.re, this->U0.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, t4.im, this->U0.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, t4.re, t4.im);
    mpz_add(tempd4, this->U0.re, this->U0.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_sub(Ud0.re, Ud0.re, temp1.re);
    mpz_sub(Ud0.im, Ud0.im, temp1.im);
    mpz_mul(tempd1, Ud0.re, this->Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, Ud0.im, this->Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, Ud0.re, Ud0.im);
    mpz_add(tempd4, this->Z.re, this->Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(Ud0.re, tempd.re);
    mpz_set(Ud0.im, tempd.im);
    mpz_sub(temp1.re, t3Z1.re, t4U11.re);
    mpz_sub(temp1.im, t3Z1.im, t4U11.im);
    mpz_mul(tempd1, temp1.re, this->U1.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, temp1.im, this->U1.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, temp1.re, temp1.im);
    mpz_add(tempd4, this->U1.re, this->U1.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_sub(Ud0.re, Ud0.re, temp1.re);
    mpz_sub(Ud0.im, Ud0.im, temp1.im);
    mpz_mul(tempd1, Ud2.re, Ud2.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, Ud2.im, Ud2.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, Ud2.re, Ud2.im);
    mpz_add(tempd4, Ud2.re, Ud2.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(ZdS.re, tempd.re);
    mpz_set(ZdS.im, tempd.im);

    // 6. V' を計算．
    // 10M, 1S
    ExtendedNumber Vd0, Vd1;
    mpz_mul(tempd1, Ud1.re, l3.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, Ud1.im, l3.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, Ud1.re, Ud1.im);
    mpz_add(tempd4, l3.re, l3.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(Vd0.re, tempd.re);
    mpz_set(Vd0.im, tempd.im);
    mpz_mul(tempd1, l2.re, Ud2.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, l2.im, Ud2.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, l2.re, l2.im);
    mpz_add(tempd4, Ud2.re, Ud2.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_sub(Vd0.re, Vd0.re, temp1.re);
    mpz_sub(Vd0.im, Vd0.im, temp1.im);
    mpz_mul(tempd1, Vd0.re, Ud0.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, Vd0.im, Ud0.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, Vd0.re, Vd0.im);
    mpz_add(tempd4, Ud0.re, Ud0.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(Vd0.re, tempd.re);
    mpz_set(Vd0.im, tempd.im);
    mpz_mul(tempd1, m.V0.re, r.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, m.V0.im, r.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, m.V0.re, m.V0.im);
    mpz_add(tempd4, r.re, r.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_add(temp1.re, temp1.re, l0.re);
    mpz_add(temp1.im, temp1.im, l0.im);
    mpz_mul(tempd1, temp1.re, ZdS.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, temp1.im, ZdS.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, temp1.re, temp1.im);
    mpz_add(tempd4, ZdS.re, ZdS.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_add(Vd0.re, Vd0.re, temp1.re);
    mpz_add(Vd0.im, Vd0.im, temp1.im);
    mpz_neg(Vd0.re, Vd0.re);
    mpz_neg(Vd0.im, Vd0.im);

    mpz_mul(tempd1, Ud1.re, Ud1.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, Ud1.im, Ud1.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, Ud1.re, Ud1.im);
    mpz_add(tempd4, Ud1.re, Ud1.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(Vd1.re, tempd.re);
    mpz_set(Vd1.im, tempd.im);
    mpz_mul(tempd1, Ud0.re, Ud2.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, Ud0.im, Ud2.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, Ud0.re, Ud0.im);
    mpz_add(tempd4, Ud2.re, Ud2.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_sub(Vd1.re, Vd1.re, temp1.re);
    mpz_sub(Vd1.im, Vd1.im, temp1.im);
    mpz_mul(tempd1, l3.re, Vd1.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, l3.im, Vd1.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, l3.re, l3.im);
    mpz_add(tempd4, Vd1.re, Vd1.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(Vd1.re, tempd.re);
    mpz_set(Vd1.im, tempd.im);
    mpz_mul(tempd1, Ud2.re, Ud1.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, Ud2.im, Ud1.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, Ud2.re, Ud2.im);
    mpz_add(tempd4, Ud1.re, Ud1.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_mul(tempd1, temp1.re, l2.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, temp1.im, l2.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, temp1.re, temp1.im);
    mpz_add(tempd4, l2.re, l2.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_sub(Vd1.re, temp1.re, Vd1.re);
    mpz_sub(Vd1.im, temp1.im, Vd1.im);
    mpz_add(temp1.re, l1.re, rV21.re);
    mpz_add(temp1.im, l1.im, rV21.im);
    mpz_mul(tempd1, temp1.re, ZdS.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, temp1.im, ZdS.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, temp1.re, temp1.im);
    mpz_add(tempd4, ZdS.re, ZdS.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_sub(Vd1.re, Vd1.re, temp1.re);
    mpz_sub(Vd1.im, Vd1.im, temp1.im);

    // 7. Z' を調整．
    // 5M
    ExtendedNumber M, Zd;
    mpz_mul(tempd1, Ud2.re, m.Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, Ud2.im, m.Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, Ud2.re, Ud2.im);
    mpz_add(tempd4, m.Z.re, m.Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(M.re, tempd.re);
    mpz_set(M.im, tempd.im);
    mpz_mul(tempd1, M.re, r.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, M.im, r.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, M.re, M.im);
    mpz_add(tempd4, r.re, r.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(M.re, tempd.re);
    mpz_set(M.im, tempd.im);
    mpz_mul(tempd1, Ud1.re, M.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, Ud1.im, M.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, Ud1.re, Ud1.im);
    mpz_add(tempd4, M.re, M.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(Ud1.re, tempd.re);
    mpz_set(Ud1.im, tempd.im);
    mpz_mul(tempd1, Ud0.re, M.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, Ud0.im, M.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, Ud0.re, Ud0.im);
    mpz_add(tempd4, M.re, M.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(Ud0.re, tempd.re);
    mpz_set(Ud0.im, tempd.im);
    mpz_mul(tempd1, Ud2.re, M.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, Ud2.im, M.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, Ud2.re, Ud2.im);
    mpz_add(tempd4, M.re, M.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(Zd.re, tempd.re);
    mpz_set(Zd.im, tempd.im);

    ExtendedProjectiveMumford ret(f, h, Ud1, Ud0, Vd1, Vd0, Zd);
    return ret;
}

ExtendedProjectiveMumford ExtendedProjectiveMumford::LangeDoubling() const{
    //std::cout << "Projective Lange Doubling." << std::endl;
    // 59M, 9S
    mpz_t temp;
    mpz_init(temp);
    ExtendedNumber tempd;
    mpz_t tempd1, tempd2, tempd3, tempd4;
    mpz_init(tempd1);
    mpz_init(tempd2);
    mpz_init(tempd3);
    mpz_init(tempd4);
    ExtendedNumber temp1, temp2;

    // 1. precomputation.
    // 3M, 2S

    ExtendedNumber U0Z, f5Z, Z2, Z3, Z4;

    mpz_mul(tempd1, this->U0.re, this->Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, this->U0.im, this->Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, this->U0.re, this->U0.im);
    mpz_add(tempd4, this->Z.re, this->Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(U0Z.re, tempd.re);
    mpz_set(U0Z.im, tempd.im);
    mpz_mul(tempd1, this->f.coeff[5].re, this->Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, this->f.coeff[5].im, this->Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, this->f.coeff[5].re, this->f.coeff[5].im);
    mpz_add(tempd4, this->Z.re, this->Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(f5Z.re, tempd.re);
    mpz_set(f5Z.im, tempd.im);
    mpz_mul(tempd1, this->Z.re, this->Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, this->Z.im, this->Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, this->Z.re, this->Z.im);
    mpz_add(tempd4, this->Z.re, this->Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(Z2.re, tempd.re);
    mpz_set(Z2.im, tempd.im);
    mpz_mul(tempd1, Z2.re, this->Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, Z2.im, this->Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, Z2.re, Z2.im);
    mpz_add(tempd4, this->Z.re, this->Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(Z3.re, tempd.re);
    mpz_set(Z3.im, tempd.im);
    mpz_mul(tempd1, Z2.re, Z2.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, Z2.im, Z2.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, Z2.re, Z2.im);
    mpz_add(tempd4, Z2.re, Z2.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(Z4.re, tempd.re);
    mpz_set(Z4.im, tempd.im);

    // 2. v~ と u の終結式を計算．
    // 4M, 2S
    ExtendedNumber V1t, V0t;
    mpz_add(V1t.re, this->V1.re, this->V1.re);
    mpz_add(V1t.im, this->V1.im, this->V1.im);
    mpz_add(V0t.re, this->V0.re, this->V0.re);
    mpz_add(V0t.im, this->V0.im, this->V0.im);

    ExtendedNumber W0, W1, U1s, W2, W3, V0tZ, r;
    mpz_mul(tempd1, this->V1.re, this->V1.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, this->V1.im, this->V1.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, this->V1.re, this->V1.im);
    mpz_add(tempd4, this->V1.re, this->V1.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(W0.re, tempd.re);
    mpz_set(W0.im, tempd.im);
    mpz_mul(tempd1, this->U1.re, this->U1.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, this->U1.im, this->U1.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, this->U1.re, this->U1.im);
    mpz_add(tempd4, this->U1.re, this->U1.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(U1s.re, tempd.re);
    mpz_set(U1s.im, tempd.im);
    mpz_add(W2.re, W0.re, W0.re);
    mpz_add(W2.im, W0.im, W0.im);
    mpz_add(W2.re, W2.re, W2.re);
    mpz_add(W2.im, W2.im, W2.im);
    mpz_mul(tempd1, this->U1.re, V1t.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, this->U1.im, V1t.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, this->U1.re, this->U1.im);
    mpz_add(tempd4, V1t.re, V1t.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(W3.re, tempd.re);
    mpz_set(W3.im, tempd.im);
    mpz_mul(tempd1, V0t.re, this->Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, V0t.im, this->Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, V0t.re, V0t.im);
    mpz_add(tempd4, this->Z.re, this->Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(V0tZ.re, tempd.re);
    mpz_set(V0tZ.im, tempd.im);
    mpz_mul(tempd1, this->U0.re, W2.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, this->U0.im, W2.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, this->U0.re, this->U0.im);
    mpz_add(tempd4, W2.re, W2.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(r.re, tempd.re);
    mpz_set(r.im, tempd.im);
    mpz_sub(temp1.re, V0tZ.re, W3.re);
    mpz_sub(temp1.im, V0tZ.im, W3.im);
    mpz_mul(tempd1, temp1.re, V0t.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, temp1.im, V0t.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, temp1.re, temp1.im);
    mpz_add(tempd4, V0t.re, V0t.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_add(r.re, r.re, temp1.re);
    mpz_add(r.im, r.im, temp1.im);

    // 3. almost inverse を計算．
    // Z がかかっている．
    //ExtendedNumber inv1d = -V1t;
    // Z^2 がかかっている．
    ExtendedNumber inv0d;
    mpz_sub(inv0d.re, V0tZ.re, W3.re);
    mpz_sub(inv0d.im, V0tZ.im, W3.im);

    // 4. k を計算．
    // 15M
    //ExtendedNumber k4 = f6;
    ExtendedNumber k4U1, k4U0Z, k3, k3U0Z, f4Z2, k2, k1, k0;
    mpz_mul(tempd1, this->f.coeff[6].re, this->U1.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, this->f.coeff[6].im, this->U1.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, this->f.coeff[6].re, this->f.coeff[6].im);
    mpz_add(tempd4, this->U1.re, this->U1.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(k4U1.re, tempd.re);
    mpz_set(k4U1.im, tempd.im);
    mpz_mul(tempd1, this->f.coeff[6].re, U0Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, this->f.coeff[6].im, U0Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, this->f.coeff[6].re, this->f.coeff[6].im);
    mpz_add(tempd4, U0Z.re, U0Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(k4U0Z.re, tempd.re);
    mpz_set(k4U0Z.im, tempd.im);
    mpz_sub(k3.re, f5Z.re, k4U1.re);
    mpz_sub(k3.im, f5Z.im, k4U1.im);
    mpz_mul(tempd1, k3.re, U0Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, k3.im, U0Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, k3.re, k3.im);
    mpz_add(tempd4, U0Z.re, U0Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(k3U0Z.re, tempd.re);
    mpz_set(k3U0Z.im, tempd.im);
    mpz_mul(tempd1, this->f.coeff[4].re, Z2.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, this->f.coeff[4].im, Z2.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, this->f.coeff[4].re, this->f.coeff[4].im);
    mpz_add(tempd4, Z2.re, Z2.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(f4Z2.re, tempd.re);
    mpz_set(f4Z2.im, tempd.im);
    mpz_mul(tempd1, k3.re, this->U1.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, k3.im, this->U1.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, k3.re, k3.im);
    mpz_add(tempd4, this->U1.re, this->U1.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(k2.re, tempd.re);
    mpz_set(k2.im, tempd.im);
    mpz_sub(k2.re, f4Z2.re, k2.re);
    mpz_sub(k2.im, f4Z2.im, k2.im);
    mpz_sub(k2.re, k2.re, k4U0Z.re);
    mpz_sub(k2.im, k2.im, k4U0Z.im);

    mpz_mul(tempd1, this->f.coeff[3].re, Z3.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, this->f.coeff[3].im, Z3.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, this->f.coeff[3].re, this->f.coeff[3].im);
    mpz_add(tempd4, Z3.re, Z3.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(k1.re, tempd.re);
    mpz_set(k1.im, tempd.im);
    mpz_sub(k1.re, k1.re, k3U0Z.re);
    mpz_sub(k1.im, k1.im, k3U0Z.im);
    mpz_mul(tempd1, k2.re, this->U1.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, k2.im, this->U1.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, k2.re, k2.im);
    mpz_add(tempd4, this->U1.re, this->U1.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_sub(k1.re, k1.re, temp1.re);
    mpz_sub(k1.im, k1.im, temp1.im);

    mpz_mul(tempd1, this->f.coeff[2].re, Z4.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, this->f.coeff[2].im, Z4.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, this->f.coeff[2].re, this->f.coeff[2].im);
    mpz_add(tempd4, Z4.re, Z4.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(k0.re, tempd.re);
    mpz_set(k0.im, tempd.im);
    mpz_mul(tempd1, W0.re, Z2.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, W0.im, Z2.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, W0.re, W0.im);
    mpz_add(tempd4, Z2.re, Z2.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_sub(k0.re, k0.re, temp1.re);
    mpz_sub(k0.im, k0.im, temp1.im);
    mpz_mul(tempd1, k2.re, U0Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, k2.im, U0Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, k2.re, k2.im);
    mpz_add(tempd4, U0Z.re, U0Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_sub(k0.re, k0.re, temp1.re);
    mpz_sub(k0.im, k0.im, temp1.im);
    mpz_mul(tempd1, k1.re, this->U1.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, k1.im, this->U1.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, k1.re, k1.im);
    mpz_add(tempd4, this->U1.re, this->U1.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_sub(k0.re, k0.re, temp1.re);
    mpz_sub(k0.im, k0.im, temp1.im);

    ExtendedNumber k1d, k0d;
    mpz_add(k1d.re, k4U0Z.re, k4U0Z.re);
    mpz_add(k1d.im, k4U0Z.im, k4U0Z.im);
    mpz_sub(k1d.re, k1d.re, k2.re);
    mpz_sub(k1d.im, k1d.im, k2.im);
    mpz_mul(tempd1, k1d.re, this->U1.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, k1d.im, this->U1.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, k1d.re, k1d.im);
    mpz_add(tempd4, this->U1.re, this->U1.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(k1d.re, tempd.re);
    mpz_set(k1d.im, tempd.im);
    mpz_sub(temp1.re, k3.re, k4U1.re);
    mpz_sub(temp1.im, k3.im, k4U1.im);
    mpz_mul(tempd1, temp1.re, U1s.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, temp1.im, U1s.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, temp1.re, temp1.im);
    mpz_add(tempd4, U1s.re, U1s.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_add(k1d.re, k1d.re, temp1.re);
    mpz_add(k1d.im, k1d.im, temp1.im);
    mpz_add(k1d.re, k1.re, k1d.re);
    mpz_add(k1d.im, k1.im, k1d.im);
    mpz_sub(k1d.re, k1d.re, k3U0Z.re);
    mpz_sub(k1d.im, k1d.im, k3U0Z.im);

    // Z^4 がかかっている．
    mpz_sub(k0d.re, k3.re, k4U1.re);
    mpz_sub(k0d.im, k3.im, k4U1.im);
    mpz_mul(tempd1, k0d.re, this->U1.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, k0d.im, this->U1.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, k0d.re, k0d.im);
    mpz_add(tempd4, this->U1.re, this->U1.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(k0d.re, tempd.re);
    mpz_set(k0d.im, tempd.im);
    mpz_add(k0d.re, k0d.re, k4U0Z.re);
    mpz_add(k0d.im, k0d.im, k4U0Z.im);
    mpz_sub(k0d.re, k0d.re, k2.re);
    mpz_sub(k0d.im, k0d.im, k2.im);
    mpz_mul(tempd1, k0d.re, U0Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, k0d.im, U0Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, k0d.re, k0d.im);
    mpz_add(tempd4, U0Z.re, U0Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(k0d.re, tempd.re);
    mpz_set(k0d.im, tempd.im);
    mpz_add(k0d.re, k0d.re, k0.re);
    mpz_add(k0d.im, k0d.im, k0.im);

    // 5. s を計算．
    // 5M
    mpz_mul(tempd1, k0d.re, inv0d.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, k0d.im, inv0d.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, k0d.re, k0d.im);
    mpz_add(tempd4, inv0d.re, inv0d.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(W0.re, tempd.re);
    mpz_set(W0.im, tempd.im);
    mpz_mul(tempd1, k1d.re, V1t.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, k1d.im, V1t.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, k1d.re, k1d.im);
    mpz_add(tempd4, V1t.re, V1t.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(W1.re, tempd.re);
    mpz_set(W1.im, tempd.im);
    mpz_neg(W1.re, W1.re);
    mpz_neg(W1.im, W1.im);
    ExtendedNumber s1d, s0d;
    mpz_sub(s1d.re, inv0d.re, V1t.re);
    mpz_sub(s1d.im, inv0d.im, V1t.im);
    mpz_add(temp1.re, k0d.re, k1d.re);
    mpz_add(temp1.im, k0d.im, k1d.im);
    mpz_mul(tempd1, s1d.re, temp1.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, s1d.im, temp1.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, s1d.re, s1d.im);
    mpz_add(tempd4, temp1.re, temp1.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(s1d.re, tempd.re);
    mpz_set(s1d.im, tempd.im);
    mpz_sub(s1d.re, s1d.re, W0.re);
    mpz_sub(s1d.im, s1d.im, W0.im);
    mpz_add(temp1.re, ExtendedNumber::ONE().re, this->U1.re);
    mpz_add(temp1.im, ExtendedNumber::ONE().im, this->U1.im);
    mpz_mul(tempd1, temp1.re, W1.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, temp1.im, W1.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, temp1.re, temp1.im);
    mpz_add(tempd4, W1.re, W1.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_sub(s1d.re, s1d.re, temp1.re);
    mpz_sub(s1d.im, s1d.im, temp1.im);
    mpz_mul(tempd1, W1.re, U0Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, W1.im, U0Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, W1.re, W1.im);
    mpz_add(tempd4, U0Z.re, U0Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(s0d.re, tempd.re);
    mpz_set(s0d.im, tempd.im);
    mpz_sub(s0d.re, W0.re, s0d.re);
    mpz_sub(s0d.im, W0.im, s0d.im);

    // 6. U' を計算．
    // 12M, 4S
    ExtendedNumber rs, f5Zk, Z3r, rsZ4;
    mpz_mul(tempd1, r.re, r.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, r.im, r.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, r.re, r.im);
    mpz_add(tempd4, r.re, r.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(rs.re, tempd.re);
    mpz_set(rs.im, tempd.im);
    mpz_sub(f5Zk.re, f5Z.re, k4U1.re);
    mpz_sub(f5Zk.im, f5Z.im, k4U1.im);
    mpz_sub(f5Zk.re, f5Zk.re, k4U1.re);
    mpz_sub(f5Zk.im, f5Zk.im, k4U1.im);
    mpz_mul(tempd1, Z3.re, r.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, Z3.im, r.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, Z3.re, Z3.im);
    mpz_add(tempd4, r.re, r.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(Z3r.re, tempd.re);
    mpz_set(Z3r.im, tempd.im);
    mpz_mul(tempd1, rs.re, Z4.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, rs.im, Z4.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, rs.re, rs.im);
    mpz_add(tempd4, Z4.re, Z4.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(rsZ4.re, tempd.re);
    mpz_set(rsZ4.im, tempd.im);

    ExtendedNumber Ud2, Ud1, V1Z3r, Ud0, Zd, Zd2;
    mpz_mul(tempd1, s1d.re, s1d.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, s1d.im, s1d.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, s1d.re, s1d.im);
    mpz_add(tempd4, s1d.re, s1d.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(Ud2.re, tempd.re);
    mpz_set(Ud2.im, tempd.im);
    mpz_mul(tempd1, rsZ4.re, this->f.coeff[6].re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, rsZ4.im, this->f.coeff[6].im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, rsZ4.re, rsZ4.im);
    mpz_add(tempd4, this->f.coeff[6].re, this->f.coeff[6].im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_sub(Ud2.re, Ud2.re, temp1.re);
    mpz_sub(Ud2.im, Ud2.im, temp1.im);

    mpz_mul(tempd1, s1d.re, s0d.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, s1d.im, s0d.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, s1d.re, s1d.im);
    mpz_add(tempd4, s0d.re, s0d.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(Ud1.re, tempd.re);
    mpz_set(Ud1.im, tempd.im);
    mpz_add(Ud1.re, Ud1.re, Ud1.re);
    mpz_add(Ud1.im, Ud1.im, Ud1.im);
    mpz_mul(tempd1, rsZ4.re, f5Zk.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, rsZ4.im, f5Zk.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, rsZ4.re, rsZ4.im);
    mpz_add(tempd4, f5Zk.re, f5Zk.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_sub(Ud1.re, Ud1.re, temp1.re);
    mpz_sub(Ud1.im, Ud1.im, temp1.im);

    mpz_mul(tempd1, this->V1.re, Z3r.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, this->V1.im, Z3r.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, this->V1.re, this->V1.im);
    mpz_add(tempd4, Z3r.re, Z3r.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(V1Z3r.re, tempd.re);
    mpz_set(V1Z3r.im, tempd.im);

    mpz_add(Ud0.re, U0Z.re, U0Z.re);
    mpz_add(Ud0.im, U0Z.im, U0Z.im);
    mpz_add(Ud0.re, Ud0.re, U1s.re);
    mpz_add(Ud0.im, Ud0.im, U1s.im);
    mpz_mul(tempd1, Ud0.re, this->f.coeff[6].re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, Ud0.im, this->f.coeff[6].im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, Ud0.re, Ud0.im);
    mpz_add(tempd4, this->f.coeff[6].re, this->f.coeff[6].im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(Ud0.re, tempd.re);
    mpz_set(Ud0.im, tempd.im);
    mpz_sub(Ud0.re, f4Z2.re, Ud0.re);
    mpz_sub(Ud0.im, f4Z2.im, Ud0.im);
    mpz_mul(tempd1, this->U1.re, f5Zk.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, this->U1.im, f5Zk.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, this->U1.re, this->U1.im);
    mpz_add(tempd4, f5Zk.re, f5Zk.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_add(temp1.re, temp1.re, temp1.re);
    mpz_add(temp1.im, temp1.im, temp1.im);
    mpz_sub(Ud0.re, Ud0.re, temp1.re);
    mpz_sub(Ud0.im, Ud0.im, temp1.im);
    mpz_mul(tempd1, rsZ4.re, Ud0.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, rsZ4.im, Ud0.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, rsZ4.re, rsZ4.im);
    mpz_add(tempd4, Ud0.re, Ud0.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(Ud0.re, tempd.re);
    mpz_set(Ud0.im, tempd.im);

    mpz_mul(tempd1, s1d.re, V1Z3r.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, s1d.im, V1Z3r.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, s1d.re, s1d.im);
    mpz_add(tempd4, V1Z3r.re, V1Z3r.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_add(temp1.re, temp1.re, temp1.re);
    mpz_add(temp1.im, temp1.im, temp1.im);
    mpz_sub(Ud0.re, temp1.re, Ud0.re);
    mpz_sub(Ud0.im, temp1.im, Ud0.im);

    mpz_mul(tempd1, s0d.re, s0d.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, s0d.im, s0d.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, s0d.re, s0d.im);
    mpz_add(tempd4, s0d.re, s0d.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_add(Ud0.re, Ud0.re, temp1.re);
    mpz_add(Ud0.im, Ud0.im, temp1.im);

    mpz_mul(tempd1, Ud1.re, Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, Ud1.im, Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, Ud1.re, Ud1.im);
    mpz_add(tempd4, Z.re, Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(Ud1.re, tempd.re);
    mpz_set(Ud1.im, tempd.im);
    mpz_mul(tempd1, Ud2.re, Z2.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, Ud2.im, Z2.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, Ud2.re, Ud2.im);
    mpz_add(tempd4, Z2.re, Z2.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(Zd.re, tempd.re);
    mpz_set(Zd.im, tempd.im);
    mpz_mul(tempd1, Zd.re, Zd.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, Zd.im, Zd.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, Zd.re, Zd.im);
    mpz_add(tempd4, Zd.re, Zd.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(Zd2.re, tempd.re);
    mpz_set(Zd2.im, tempd.im);

    // 7. V' を計算．
    // 15M, 1S
    // r Z^7 がかかっている．
    ExtendedNumber l3, l2, l1, l0, l2Zd;
    mpz_mul(tempd1, s1d.re, Z2.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, s1d.im, Z2.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, s1d.re, s1d.im);
    mpz_add(tempd4, Z2.re, Z2.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(l3.re, tempd.re);
    mpz_set(l3.im, tempd.im);
    mpz_mul(tempd1, s1d.re, this->U1.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, s1d.im, this->U1.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, s1d.re, s1d.im);
    mpz_add(tempd4, this->U1.re, this->U1.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(l2.re, tempd.re);
    mpz_set(l2.im, tempd.im);
    mpz_add(l2.re, l2.re, s0d.re);
    mpz_add(l2.im, l2.im, s0d.im);
    mpz_mul(tempd1, l2.re, this->Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, l2.im, this->Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, l2.re, l2.im);
    mpz_add(tempd4, this->Z.re, this->Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(l2.re, tempd.re);
    mpz_set(l2.im, tempd.im);
    mpz_mul(tempd1, s1d.re, U0Z.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, s1d.im, U0Z.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, s1d.re, s1d.im);
    mpz_add(tempd4, U0Z.re, U0Z.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(l1.re, tempd.re);
    mpz_set(l1.im, tempd.im);
    mpz_mul(tempd1, s0d.re, this->U1.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, s0d.im, this->U1.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, s0d.re, s0d.im);
    mpz_add(tempd4, this->U1.re, this->U1.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_add(l1.re, l1.re, temp1.re);
    mpz_add(l1.im, l1.im, temp1.im);
    mpz_mul(tempd1, s0d.re, this->U0.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, s0d.im, this->U0.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, s0d.re, s0d.im);
    mpz_add(tempd4, this->U0.re, this->U0.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(l0.re, tempd.re);
    mpz_set(l0.im, tempd.im);
    mpz_mul(tempd1, l2.re, Zd.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, l2.im, Zd.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, l2.re, l2.im);
    mpz_add(tempd4, Zd.re, Zd.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(l2Zd.re, tempd.re);
    mpz_set(l2Zd.im, tempd.im);

    ExtendedNumber Vd1, Vd0;
    mpz_mul(tempd1, Ud1.re, Ud1.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, Ud1.im, Ud1.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, Ud1.re, Ud1.im);
    mpz_add(tempd4, Ud1.re, Ud1.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(Vd1.re, tempd.re);
    mpz_set(Vd1.im, tempd.im);
    mpz_mul(tempd1, Ud0.re, Zd.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, Ud0.im, Zd.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, Ud0.re, Ud0.im);
    mpz_add(tempd4, Zd.re, Zd.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_sub(Vd1.re, Vd1.re, temp1.re);
    mpz_sub(Vd1.im, Vd1.im, temp1.im);
    mpz_mul(tempd1, Vd1.re, l3.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, Vd1.im, l3.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, Vd1.re, Vd1.im);
    mpz_add(tempd4, l3.re, l3.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(Vd1.re, tempd.re);
    mpz_set(Vd1.im, tempd.im);
    mpz_mul(tempd1, Ud1.re, l2Zd.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, Ud1.im, l2Zd.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, Ud1.re, Ud1.im);
    mpz_add(tempd4, l2Zd.re, l2Zd.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_sub(Vd1.re, temp1.re, Vd1.re);
    mpz_sub(Vd1.im, temp1.im, Vd1.im);
    mpz_add(temp1.re, l1.re, V1Z3r.re);
    mpz_add(temp1.im, l1.im, V1Z3r.im);
    mpz_mul(tempd1, temp1.re, Zd2.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, temp1.im, Zd2.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, temp1.re, temp1.im);
    mpz_add(tempd4, Zd2.re, Zd2.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_sub(Vd1.re, Vd1.re, temp1.re);
    mpz_sub(Vd1.im, Vd1.im, temp1.im);

    mpz_mul(tempd1, l3.re, Ud1.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, l3.im, Ud1.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, l3.re, l3.im);
    mpz_add(tempd4, Ud1.re, Ud1.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(Vd0.re, tempd.re);
    mpz_set(Vd0.im, tempd.im);
    mpz_sub(Vd0.re, Vd0.re, l2Zd.re);
    mpz_sub(Vd0.im, Vd0.im, l2Zd.im);
    mpz_mul(tempd1, Vd0.re, Ud0.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, Vd0.im, Ud0.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, Vd0.re, Vd0.im);
    mpz_add(tempd4, Ud0.re, Ud0.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(Vd0.re, tempd.re);
    mpz_set(Vd0.im, tempd.im);
    mpz_mul(tempd1, this->V0.re, Z3r.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, this->V0.im, Z3r.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, this->V0.re, this->V0.im);
    mpz_add(tempd4, Z3r.re, Z3r.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_add(temp1.re, temp1.re, l0.re);
    mpz_add(temp1.im, temp1.im, l0.im);
    mpz_mul(tempd1, temp1.re, Zd2.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, temp1.im, Zd2.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, temp1.re, temp1.im);
    mpz_add(tempd4, Zd2.re, Zd2.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(temp1.re, tempd.re);
    mpz_set(temp1.im, tempd.im);
    mpz_add(Vd0.re, Vd0.re, temp1.re);
    mpz_add(Vd0.im, Vd0.im, temp1.im);
    mpz_neg(Vd0.re, Vd0.re);
    mpz_neg(Vd0.im, Vd0.im);

    // 8. 調整
    // 5M
    ExtendedNumber ZM;
    mpz_mul(tempd1, Z4.re, Zd.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, Z4.im, Zd.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, Z4.re, Z4.im);
    mpz_add(tempd4, Zd.re, Zd.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(ZM.re, tempd.re);
    mpz_set(ZM.im, tempd.im);
    mpz_mul(tempd1, ZM.re, r.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, ZM.im, r.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, ZM.re, ZM.im);
    mpz_add(tempd4, r.re, r.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(ZM.re, tempd.re);
    mpz_set(ZM.im, tempd.im);
    mpz_mul(tempd1, Ud1.re, ZM.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, Ud1.im, ZM.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, Ud1.re, Ud1.im);
    mpz_add(tempd4, ZM.re, ZM.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(Ud1.re, tempd.re);
    mpz_set(Ud1.im, tempd.im);
    mpz_mul(tempd1, Ud0.re, ZM.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, Ud0.im, ZM.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, Ud0.re, Ud0.im);
    mpz_add(tempd4, ZM.re, ZM.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(Ud0.re, tempd.re);
    mpz_set(Ud0.im, tempd.im);
    mpz_mul(tempd1, Zd.re, ZM.re);
    mpz_mod(tempd1, tempd1, ExtendedNumber::CHARA);
    mpz_mul(tempd2, Zd.im, ZM.im);
    mpz_mod(tempd2, tempd2, ExtendedNumber::CHARA);
    mpz_sub(tempd.re, tempd1, tempd2);
    mpz_add(tempd3, Zd.re, Zd.im);
    mpz_add(tempd4, ZM.re, ZM.im);
    mpz_mul(tempd.im, tempd3, tempd4);
    mpz_mod(tempd.im, tempd.im, ExtendedNumber::CHARA);
    mpz_sub(tempd.im, tempd.im, tempd1);
    mpz_sub(tempd.im, tempd.im, tempd2);
    mpz_set(Zd.re, tempd.re);
    mpz_set(Zd.im, tempd.im);

    ExtendedProjectiveMumford ret(f, h, Ud1, Ud0, Vd1, Vd0, Zd);
    return ret;
}

ExtendedProjectiveMumford ExtendedProjectiveMumford::zero(const ExtendedPolynomial& f, const ExtendedPolynomial& h){
    ExtendedProjectiveMumford zero(f, h);
    return zero;
}

bool ExtendedProjectiveMumford::isZero() const{
    if(V1.isZero() && V0.isZero()){
        if(U1.isZero() && U0 == ExtendedNumber::ONE()){
            return true;
        }
    }
    return false;
}

void ExtendedProjectiveMumford::print() const{
    std::cerr << "[" << U1 << ", " << U0 << "]" << std::endl;
    std::cerr << "[" << V1 << ", " << V0 << "]" << std::endl;
    return;
}
